In [2]:
#Task 1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
import numpy as np
a = np.linspace(1, 10, num=10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
#Task 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
b = np.zeros((3, 3), dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#Task 3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
c = np.random.randint(1, 10, size=(5, 5))
print(c)

[[5 6 3 2 7]
 [4 2 5 1 4]
 [5 9 8 3 9]
 [5 1 1 4 4]
 [1 2 3 8 5]]


In [ ]:
#task 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
d = np.random.random((4, 4))
print(d)

[[0.33852784 0.98826414 0.26941539 0.32251765]
 [0.56250617 0.13451488 0.19130749 0.00745331]
 [0.05734241 0.63786662 0.97192801 0.0213514 ]
 [0.29937429 0.7343855  0.74558729 0.42365391]]


In [ ]:
#Task 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
e1 = np.random.randint(1, 10, size=(1, 5))
e2 = np.random.randint(1, 10, size=(1, 5))
e3 = e1 + e2
e4 = e1 - e2
e5 = e2 - e1
e6 = e1*e2
print("e1 = ", e1)
print("e2 = ", e2)
print("e1 + e2 = ", e3)
print("e1 - e2 = ", e4)
print("e2 - e1 = ", e5)
print("e1*e2 = ", e6)

e1 =  [[4 9 7 3 9]]
e2 =  [[6 6 7 9 5]]
e1 + e2 =  [[10 15 14 12 14]]
e1 - e2 =  [[-2  3  0 -6  4]]
e2 - e1 =  [[ 2 -3  0  6 -4]]
e1*e2 =  [[24 54 49 27 45]]


In [34]:
#Task 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
f1 = np.array([1, 2, 3, 4, 5, 6, 7], dtype=float)
f2 = np.array([11, 12, 13, 14, 15, 16, 17], dtype=float)
f3 = f1@f2
f4 = np.dot(f1, f2)
print(f1)
print(f2)
print(f3)
print(f4)

[1. 2. 3. 4. 5. 6. 7.]
[11. 12. 13. 14. 15. 16. 17.]
420.0
420.0


In [ ]:
#Task 7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
g1 = np.random.randint(1, 10, size=(2, 2))
g2 = np.random.randint(1, 10, size=(2, 3))
g3 = np.dot(g1, g2)
print("First matrix: \n", g1)
print("Second matrix: \n", g2)
print("Result of multiplication: \n", g3)

First matrix: 
 [[3 2]
 [5 4]]
Second matrix: 
 [[1 2 5]
 [9 6 2]]
Result of multiplication 
 [[21 18 19]
 [41 34 33]]


In [ ]:
#Task 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
h1 = np.random.randint(1, 10, size=(3, 3))
h2 = np.linalg.inv(h1)
print("Matrix: \n", h1)
print("Reversed matrix: \n", h2)

[[8 8 1]
 [4 3 8]
 [8 6 4]]
[[-0.375      -0.27083333  0.63541667]
 [ 0.5         0.25       -0.625     ]
 [ 0.          0.16666667 -0.08333333]]


In [ ]:
#Task 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
j1 = np.random.random((4, 4))
j2 = j1.T
print("Matrix: \n", j1)
print("Transposed matrix: \n", j2)

Matrix: 
 [[0.31074508 0.41865741 0.62862865 0.38166726]
 [0.78682882 0.70247066 0.77471964 0.55303691]
 [0.4765392  0.07524895 0.01096708 0.27612284]
 [0.22181514 0.7282292  0.54818802 0.57475205]]
Transposed matrix: 
 [[0.31074508 0.78682882 0.4765392  0.22181514]
 [0.41865741 0.70247066 0.07524895 0.7282292 ]
 [0.62862865 0.77471964 0.01096708 0.54818802]
 [0.38166726 0.55303691 0.27612284 0.57475205]]


In [ ]:
#Task 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
k1 = np.random.randint(1, 10, size=(3, 4))
k2 = np.random.randint(1, 10, size=(4))
print("Matrix: \n", k1)
print("Vector: \n", k2)
print("Result of multiplication: \n", k1*k2)

Matrix: 
 [[7 7 5 4]
 [6 1 2 7]
 [1 5 6 8]]
Vector: 
 [1 2 1 2]
Result of multiplication: 
 [[ 7 14  5  8]
 [ 6  2  2 14]
 [ 1 10  6 16]]


In [ ]:
#Task 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
l1 = np.random.random((2, 3))
l2 = np.random.random((3))
print("Matrix: \n", l1)
print("Vector \n", l2)
print("Result of multiplicatio: \n", l1*l2)

Matrix: 
 [[0.47176313 0.68036565 0.72572885]
 [0.82240708 0.31809932 0.45517601]]
Vector 
 [0.63817513 0.70470303 0.7946945 ]
Result of multiplicatio: 
 [[0.3010675  0.47945574 0.57673273]
 [0.52483974 0.22416555 0.36172587]]


In [ ]:
#Task 12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
m1 = np.random.randint(1, 10, size=(2, 2))
m2 = np.random.randint(1, 10, size=(2, 2))
print("First matrix: \n", m1)
print("Second matrix: \n", m2)
print("The result of element-by-element multiplication: \n", m1*m2)

First matrix: 
 [[6 5]
 [9 3]]
Second matrix: 
 [[5 4]
 [2 3]]
The result of element-by-element multiplication: 
 [[30 20]
 [18  9]]


In [ ]:
#Task 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
n1 = np.random.randint(1, 10, size=(2, 2))
n2 = np.random.randint(1, 10, size=(2, 2))
n3 = np.dot(n1, n2)
print("First matrix: \n", n1)
print("Second matrix: \n", n2)
print("Result of multiplication: \n", n3)

First matrix: 
 [[8 9]
 [5 5]]
Second matrix: 
 [[2 9]
 [8 2]]
Result of multiplication: 
 [[88 90]
 [50 55]]


In [29]:
#Task 14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
o1 = np.random.randint(1, 100, size=(5, 5))
o2 = np.sum(o1)
o3 = o1.flatten().sum()
print("Matrix: \n", o1)
print("Summa: \n", o3)
print("Summa: \n", o2)

Matrix: 
 [[26 71 25 54 40]
 [49 53 22 85 57]
 [62 58 34 34 62]
 [65 38 76 29 28]
 [24 94 58 29 75]]
Summa: 
 1248
Summa: 
 1248


In [36]:
#Task 15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
p1 = np.random.randint(1, 10, size=(4, 4))
p2 = np.random.randint(1, 10, size=(4, 4))
p3 = p1 - p2
p4 = p2 - p1
print("First matrix: \n", p1)
print("Second matrix: \n", p2)
print("Result of the subtraction: \n", p3)
print("Result of the subtraction: \n", p4)

First matrix: 
 [[1 9 2 5]
 [1 9 7 1]
 [2 3 2 8]
 [4 3 1 7]]
Second matrix: 
 [[4 2 2 4]
 [6 9 5 3]
 [7 1 5 9]
 [9 4 9 4]]
Result of the subtraction: 
 [[-3  7  0  1]
 [-5  0  2 -2]
 [-5  2 -3 -1]
 [-5 -1 -8  3]]
Result of the subtraction: 
 [[ 3 -7  0 -1]
 [ 5  0 -2  2]
 [ 5 -2  3  1]
 [ 5  1  8 -3]]


In [41]:
#Task 16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
q = np.random.random((3, 3))
q4 = np.array([[q[0, :].sum()], [q[1, :].sum()], [q[2, :].sum()]], dtype = float)
q5 = np.column_stack(q.sum(axis=1)).T
print("Matrix: \n", q)
print("Vector-column: \n", q4)
print("Vector: \n",q5)

Matrix: 
 [[0.84789743 0.99088805 0.11276668]
 [0.53020833 0.44505048 0.84147807]
 [0.90590906 0.12101422 0.99920614]]
Vector-column: 
 [[1.95155217]
 [1.81673688]
 [2.02612943]]
Vector: 
 [[1.95155217]
 [1.81673688]
 [2.02612943]]


In [30]:
#Task 17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
r1 = np.random.randint(1, 10, size=(3, 4))
r2 = np.multiply(r1,r1)
r3 = np.power(r1, 2)
r4 = np.square(r1)
print("Matrix: \n", r1)
print("Matrix of their squares of numbers: \n", r2)
print("Matrix of their squares of numbers: \n", r3)
print("Matrix of their squares of numbers: \n", r4)

Matrix: 
 [[9 5 5 9]
 [2 1 4 7]
 [8 5 3 6]]
Matrix of their squares of numbers: 
 [[81 25 25 81]
 [ 4  1 16 49]
 [64 25  9 36]]
Matrix of their squares of numbers: 
 [[81 25 25 81]
 [ 4  1 16 49]
 [64 25  9 36]]
Matrix of their squares of numbers: 
 [[81 25 25 81]
 [ 4  1 16 49]
 [64 25  9 36]]


In [19]:
#Task 18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
s1 = np.random.randint(1, 50, size=(1, 4))
s2 = np.sqrt(s1)
print("Vector: \n", s1)
print("Vector with square roots of numbers: \n", s2)

Vector: 
 [[33 16 39 39]]
Vector with square roots of numbers: 
 [[5.74456265 4.         6.244998   6.244998  ]]
