In [1]:
import pandas as pd
import numpy as np
#напишіть функцію гіпотези лінійної регресії у векторному вигляді;
def gip_lin_reg(X: pd.Series, w: pd.Series):
  h_result = np.dot(X, w)
  return h_result

In [3]:
#створіть функцію для обчислення функції втрат у векторному вигляді;
def loss_vecto(X: pd.Series, w: pd.Series, y: pd.Series):
  m = len(y)
  h = gip_lin_reg(X, w)
  error = h - y
  return (1/m) * np.sum(error**2)

In [4]:
#реалізуйте один крок градієнтного спуску;
def grad_step(X, y, w, leaning_rate):
    m = len(y)
    h = gip_lin_reg(X, w)
    error = h - y
    gradient = np.dot(X.T, error)
    w = w - leaning_rate*gradient
    return w

In [12]:
#знайдіть найкращі параметри для датасету прогнозуючу ціну на будинок залежно від площі, кількості ванних кімнат та кількості спалень;
from sklearn.linear_model import LinearRegression
data_set_2 = pd.read_csv("Housing.csv")
data_x_2 = pd.concat([data_set_2['area'], data_set_2['bedrooms'], data_set_2['bathrooms']], axis = 1)
X = pd.concat([pd.Series(np.ones(data_x_2.shape[0])), data_x_2], axis = 1)
y = pd.DataFrame(data = data_set_2['price'], dtype = int)
w = np.zeros((data_x_2.shape[1]+1, 1))
w_new = grad_step(X, y, w, 0.00000003)
loss_new = loss_vecto(X, w_new, y)
for i in range(3):
  w_new = grad_step(X, y, w_new, 0.00000001)
  loss_new = loss_vecto(X, w_new, y)
  print(w_new.astype(int))
  print(loss_new.astype(int))


[[   -12160]
 [-73780227]
 [   -36625]
 [   -16133]]
price   -9223372036854775808
dtype: int64
[[    2058910]
 [12483598629]
 [    6202012]
 [    2732587]]
price   -9223372036854775808
dtype: int64
[[    -348361425]
 [-2112197428113]
 [   -1049360606]
 [    -462344269]]
price   -9223372036854775808
dtype: int64


In [8]:
#знайдіть ці ж параметри за допомогою аналітичного рішення;
from sklearn.linear_model import LinearRegression
data_set = pd.read_csv("Housing.csv")
lr = LinearRegression()
data_x = pd.concat([data_set['area'], data_set['bedrooms'], data_set['bathrooms']], axis = 1)
# print(data_x)
lr.fit(data_x, data_set['price'])

data_set['Прогноз'] = lr.predict(data_x).astype(int)
data_set['Залишок'] = data_set['price'] - data_set['Прогноз']
print(data_set)
print(np.min(np.sqrt(data_set['Залишок']**2)))
print(f"Intercept from sklearn: {lr.intercept_}")
print(f"Coefficients from sklearn: {lr.coef_.astype(int)}")

        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating aircond

In [9]:
#порівняйте отримані результати.
print(f"{lr.intercept_} {lr.coef_.astype(int)}")
print(w_new.astype(int))

-173171.6076326361 [    378  406820 1386049]
[[-9223372036854775808]
 [-9223372036854775808]
 [-9223372036854775808]
 [-9223372036854775808]]
